### ISSUE TITLE
File is missing

### ISSUE THREAD

**Issue by DDholiyan** [omerkamcili/ci_google_calendar_api#2]
require APPPATH . "third_party/google-api-php-client/src/Google/autoload.php";

This file is not present in the directory. How can I get this?

**Comment by omerkamcili** [comment]
I push it on project and changed folder name. 
New folder name /third_party/google-api-php/ and edit googleplus library.
Commits https://github.com/omerkamcili/ci_google_calendar_api/commit/f216ddbbf21f114639a19225280c8869bcfa392e for look changes.

**Comment by DDholiyan** [comment]
Below is something need to take from google as described in first step of read me?

Type: Google_Exception

Message: Invalid client secret JSON file.

Filename: D:\xampp\htdocs\ci_google_calendar_api-master\application\third_party\google-api-php\src\Google\Client.php

**Comment by omerkamcili** [comment]
*Current json file is empty, create your json auth file from https://console.developers.google.com/apis/credentials, 
*Paste to /application/config/ folder your json file
*Edit application/library/Googleplus.php line 13, replace json file name with your new json file

**Comment by DDholiyan** [comment]
Thanks a lot. I will :+1:

**Comment by omerkamcili** [comment]
Not at all :)

**Comment by DDholiyan** [comment]
I have setup this, Thanks

But Now I have below issue:-

When I enter url  like:- http://localhost/ci_google_calendar_api-master it redirects to 
$config['base_url'] = 'http://apitest.dev';

But i have changed this with below:-

$root  = "http://".$_SERVER['HTTP_HOST'];
$root .= str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);
$config['base_url']    = $root;

and now this goes to:-

http://localhost/ci_google_calendar_api-master/auth/login and this shows 'Object not found'.

I checked apache error log this says:-

[Fri Jul 29 16:31:37.695373 2016] [:error] [pid 5424:tid 1696] [client ::1:49758] PHP Fatal error:  require(): Failed opening required 'D:\xampp\htdocs\ci_google_calendar_api-master\application\third_party/google-api-php/src/Google/autoload.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\ci_google_calendar_api-master\application\libraries\Googleplus.php on line 8

Why I am getting this error, please help.

**Comment by omerkamcili** [comment]
This folder is exist? D:\xampp\htdocs\ci_google_calendar_api-master\application\third_party/google-api-php/

I changed folder name last commit.

**Comment by DDholiyan** [comment]
yes, All files are in this folder google-api-php and google-api-php-client is blank.

I download new directory after your last commit.

**Comment by omerkamcili** [comment]
Very interesting, everything is correct this error should not

**Comment by omerkamcili** [comment]
You can try delete all files and clone again from repo, maybe there was something missing.

**Comment by DDholiyan** [comment]
Ok I will, Thanks
