### ISSUE TITLE
i have some issue please check below description

### ISSUE THREAD

**Issue by hardikdayani1** [omerkamcili/ci_google_calendar_api#3]
first i am click on Sign in with Google link and go to select gmail account and i am select account after then stop my page please below error.

My requirement create event in google calendar using php please reply me

![issue](https://user-images.githubusercontent.com/29699079/30913724-c9955146-a3ae-11e7-8a70-9f888a35fe80.png)

**Comment by kuldeepsinghgit** [comment]
wewe

**Comment by ntipitagoras** [comment]
Estou com o mesmo problema, alguém conseguiu resolver?

**Comment by omerkamcili** [comment]
Hi everyone, i sent some changes, please pull repo and check it again.

**Comment by ntipitagoras** [comment]
Thank you bro
