### ISSUE TITLE
help. Error 400 (OAuth2 Error)!!1

### ISSUE THREAD

**Issue by dikadittya** [omerkamcili/ci_google_calendar_api#5]
400. That’s an error.

Error: invalid_request

Missing required parameter: redirect_uri

**Comment by omerkamcili** [comment]
You must enter authorized redirect uri in your application settings page in google. **http://your-host/auth/oauth**

![ekran resmi 2018-04-19 17 56 04](https://user-images.githubusercontent.com/11783296/38999790-47b80b8a-43fb-11e8-8293-c99abfcb5daa.png)
