### ISSUE TITLE
Not redirecting to add event method to put some events

### ISSUE THREAD

**Issue by kuldeepsinghgit** [omerkamcili/ci_google_calendar_api#6]
Hi 
I am new to integrate google calendar api i am not sure what link i have to put  to redirect the addevent method in json file.
redirect_uris":["http://localhost/ci_google_calendar_api-master/event/addevent"],"

Please help us

**Comment by omerkamcili** [comment]
Hi, You must use this uri **http://localhost/auth/oauth** you can see in config/route.php
